### ISSUE TITLE
Design the message to be shown post-submission and redirect to Feedback form

### ISSUE THREAD

**Issue by paarugsethi** [SuperteamDAO/earn#270]
Once someone has submitted a bounty, a popup needs to be shown to users for feedback about Superteam Earn.

**Copy:** Help Us Improve Superteam Earn 
**Text:** We'd love to know about your expereince with Earn, and how we can improve!

Clicking on the popup should redirect the user to [this form](https://airtable.com/app59bjxK4v1M4SEU/shrNNnUArMlpK5bj9).

![image](https://github.com/SuperteamDAO/earn/assets/87030959/6483cc25-f306-475c-a04c-a2051f423a76)

**Comment by iamsatyajit05** [comment]
Hey, is there any guide of setting up the project locally? I am having lots of errors :(

**Comment by ATREAY** [comment]
Hi @a20hek, I've included the popup as required. Could you please take a look whenever you have a moment?

**Comment by a20hek** [comment]
> Hey, is there any guide of setting up the project locally? I am having lots of errors :(

we have a README.md with setup instructions.
