### ISSUE TITLE
Sort Comments in Reverse Chronological order

### ISSUE THREAD

**Issue by paarugsethi** [SuperteamDAO/earn#271]
Comments under bounties are currently sorted in chronological order i.e. newest is at the top. Change this order to reverse chronological so that newest comments show up at the bottom.

**Comment by ATREAY** [comment]
Hey @paarugsethi, can I work on this issue?

**Comment by ATREAY** [comment]
Hey @a20hek, I was trying to set things up locally and ran into an error. It seems I might need some environment variables. I tried to hit you up on Twitter about it, but it looks like your DMs are locked.

**Comment by a20hek** [comment]
hey @ATREAY can you try again?

**Comment by ATREAY** [comment]
Hey @a20hek, I've sent you a DM. Please check when you have time.

**Comment by ATREAY** [comment]
Hey @a20hek and @paarugsethi, I've made the necessary changes. Could you please take a look?

**Comment by ATREAY** [comment]
Hey @a20hek, I've sorted out the lint error. Could you give it a look and tell me if there's anything else left to do?

**Comment by ATREAY** [comment]
Hey @a20hek, you marked this issue as "not planned." Does that mean I should close my PR, or is there another action needed?
