### ISSUE TITLE
Update the UI and UX of liking a submission

### ISSUE THREAD

**Issue by paarugsethi** [SuperteamDAO/earn#273]
Two improvements to be made:

- The whole page reloads after liking a submission right now. This is not ideal and should be fixed.
- Improve how the toaster looks visually.

![image](https://github.com/SuperteamDAO/earn/assets/87030959/fcaa83dd-be8d-499e-afdb-9869a7f5cf30)

**Comment by a20hek** [comment]
@nawed2611 dm me on twitter, will send you the env

**Comment by nawed2611** [comment]
DMs seems to be closed

**Comment by a20hek** [comment]
> DMs seems to be closed

can you try again?

**Comment by nawed2611** [comment]
Just a question -- can I not view submissions made on dev env?

**Comment by a20hek** [comment]
wdym

**Comment by nawed2611** [comment]
Sorry for the confusion - Just created a PR #281
