### ISSUE TITLE
Pre-fill "Start from Scratch" for new bounties with the following headers

### ISSUE THREAD

**Issue by paarugsethi** [SuperteamDAO/earn#274]
Pre-fill the bounty description dialog box with these headings. All of these should be in H1 font: 

- About the Bounty & Scope 
- Rewards 
- Judging Criteria
- Submission Requirements
- Resources

Any user should be able to delete these but should come pre-filled when making a new bounty.

**Comment by Sagargajare** [comment]
I want to contribute. Can I pick this issue?

**Comment by suhasasumukh** [comment]
hey @paarugsethi I have opened a pull request for this issue, please do check it - https://github.com/SuperteamDAO/earn/pull/305

**Comment by yash431garg** [comment]
Is @suhasasumukh is this issue closed?

**Comment by a20hek** [comment]
> Hi @suhasasumukh is this issue closed?

nope

**Comment by Dprof-in-tech** [comment]
hi @a20hek 
I want to work on this issue...

may I do that?

**Comment by a20hek** [comment]
can start working on any issues without worries!
no need to ask for a permission. we believe in permissionless work here @Dprof-in-tech
