### ISSUE TITLE
Add SOL Faucet to the Talent Creation Flow

### ISSUE THREAD

**Issue by paarugsethi** [SuperteamDAO/earn#276]
- Airdrop 0.001 SOL to everyone who creates a profile
- Add to messaging as well "Create a profile and get enough SOL for 10 transactions on Solana"
- Find the faucet [here](https://solfaucet.fun/).

**Comment by vishalpokuri** [comment]
Do you want it like 
1. Redirection to the solfaucet just after completing the profile creation or
2. Directly airdropping 0.001 Sol and letting them know after doing it?

**Comment by thisissamridh** [comment]
@paarugsethi  Can you assign it to me to no one is doing it .
