### ISSUE TITLE
Add project to Hacktoberfest

### ISSUE THREAD

**Issue by akshatcoder-hash** [SuperteamDAO/earn#277]
## Adding a Project to Hacktoberfest:

- Add the “hacktoberfest” topic to your repository to opt-in to Hacktoberfest and indicate you’re looking for contributions.

![image](https://github.com/SuperteamDAO/earn/assets/69577224/4435fadb-dc76-4368-bbf0-5c3935c59f74)

- Apply the “hacktoberfest” label to issues you want contributors to help with in your GitHub or GitLab project.
- Add a CONTRIBUTING.md file with contribution guidelines to your repository.
- Choose issues that have a well-defined scope and are self-contained.
- Adopt a code of conduct to create a greater sense of inclusion and community for contributors.
- Be ready to review pull/merge requests, accepting those that are valid by merging them, leaving an overall approving review, or by adding the “hacktoberfest-accepted” label.
- Reject any spammy requests you receive by labeling them as “spam,” and any other invalid contributions by closing them or labeling them as “invalid.”

More details on the [official page](https://hacktoberfest.com/participation/#maintainers)

**Comment by a20hek** [comment]
missed this!
can do this during the next hacktoberfest
thanks for the suggestion @akshatcoder-hash !
