### ISSUE TITLE
Twitter logo update required across the web-app

### ISSUE THREAD

**Issue by tmsagarofficial** [SuperteamDAO/earn#279]
## Expected Behavior
 Updated logo of the Twitter
## Actual Behavior
 The old blue bird logo of Twitter
## Steps to Reproduce the Problem

1. Go to https://earn.superteam.fun
2. Scroll till the bottom of the page
3. Notice the old Twitter logo in the footer section
4. 
<img width="353" alt="image" src="https://github.com/SuperteamDAO/earn/assets/110724849/e02f36ad-aa95-4c6c-ada7-f021caf715c6">

Pls assign this issue to e so that I can work on a fix for this issue @a20hek

**Comment by a20hek** [comment]
you can start working nevertheless. just raise a PR through this issue

**Comment by Pawank06** [comment]
Hey can I want to work on this issue. can I make a PR?

**Comment by suhasasumukh** [comment]
Hey, I have made a PR on this issue,

PR link: https://github.com/SuperteamDAO/earn/pull/282

**Comment by a20hek** [comment]
while you mentioned the Twitter logo update in the footer, upon review, we realized that the logo needs to be updated across various parts of the web app. we'll be making the necessary changes not only in the footer but everywhere it's relevant

if you're interested in contributing further, feel free to submit a PR addressing this broader scope or let us know if you have spotted any other inconsistencies or areas of improvement.

cc: @tmsagarofficial @suhasasumukh @Pawank06

**Comment by suhasasumukh** [comment]
May I know the other places where you would like to change the logo?

cc: @a20hek

**Comment by suhasasumukh** [comment]
hey @tmsagarofficial this is fixed now
