### ISSUE TITLE
Authentication state persistance

### ISSUE THREAD

**Issue by jim4067** [SuperteamDAO/earn#356]
## Expected Behavior
When navigating the earn website between different routes I would like for my wallet state to be persisted unless I log out

## Actual Behavior
I get disconnected from my wallet

## Steps to Reproduce the Problem

1. go to the earn website
2. connect wallet
3. switch between different routes and your wallet connection gets disconnected.

## possible fix
use context or a state management library e.g zustand or recoil

**Comment by a20hek** [comment]
this has been solved in an upcoming feature branch. thanks!
