### ISSUE TITLE
Resolve Hydration Errors

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#364]
## Expected Behavior
- The web-app should render consistently on both the server and the client, ensuring a smooth hydration process without errors.
- The initial UI rendered by the server should match the UI rendered on the client.

## Actual Behavior
- The application is experiencing hydration errors, as indicated by the error message: "Error: Hydration failed because the initial UI does not match what was rendered on the server."

## Steps to Reproduce the Problem
1. Run the app using `pnpm dev`
2. Observe the localhost for hydration error messages during page load.

**Comment by Sumit-Kumar-21** [comment]
Ohh that is what i was facing.

**Comment by joshuanazareth97** [comment]
Is this issue still open? Or fixed already?

**Comment by a20hek** [comment]
it's open @joshuanazareth97

**Comment by a20hek** [comment]
has been fixed by me, so closing
