### ISSUE TITLE
Match the design of the profile creation success page to the figma link

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#411]
The design as of now looks very out of place: 
<img width="704" alt="image" src="https://github.com/SuperteamDAO/earn/assets/67309069/3ae9e802-a0d5-4bbf-b95a-da3ebd0ba443">

Match the design of those two cards with the one in the following figma link: https://www.figma.com/file/32RTTrXJb8MQo8bz833ioA?embed_host=oembed&kind=file&node-id=2033-860&type=design&viewer=1

## Steps to Reproduce the Problem

1. Create a talent profile
2. Get to the success page

**Comment by apneduniya** [comment]
What exactly you expect?? Design implementation in profile page or something else??

**Comment by a20hek** [comment]
> What exactly you expect?? Design implementation in profile page or something else??

design implementation
