### ISSUE TITLE
Reduce the random numbers added to a username to make it more memorable

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#412]
## Expected Behavior
Usernames suggested during account creation should be easy to remember while maintaining uniqueness. Ideally, a username should be a concatenation of the user's name and a short sequence of numbers to ensure uniqueness without making it cumbersome.

## Actual Behavior
The current username generation algorithm/approach suggests usernames with long strings of numbers appended, such as "dholanipratik973551". This makes the username difficult to remember and unnecessarily long, potentially impacting user experience.
<img width="582" alt="image" src="https://github.com/SuperteamDAO/earn/assets/67309069/6116dbae-8be8-4091-ba55-086d0376bf59">

**Comment by gulshanpr** [comment]
I would like to work on this.

**Comment by gulshanpr** [comment]
Hii @a20hek ,

My observations:
1. I think [this](https://github.com/SuperteamDAO/earn/blob/07b7377f905336d61d751122a22bdd8933309c13/src/pages/api/user/create.ts#L8) username variable is not able to generate or suggest the user name to user on the front end part.
2. I am able to create any user name from 1 letter to 52 (till i tested) or more.

Suggested change:
1. when user is creating account, the auto suggested user should be already auto filled there.
2. cap username letter to 20-24.

Question:
1. where i can find, what user name is being suggested while creating account as described in the issue's image?

Thank You.

**Comment by a20hek** [comment]
> 1. where i can find, what user name is being suggested while creating account as described in the issue's image?

you can find it when you try to create an account?

**Comment by gulshanpr** [comment]
> you can find it when you try to create an account?


![image](https://github.com/SuperteamDAO/earn/assets/115975801/bfa716cb-d958-4a3c-8d94-b82148ad5c09)
no, it is not working in my case.

**Comment by a20hek** [comment]
damn, we seemed to have solved it recently but forgot to document it. thanks for pointing this out!
