### ISSUE TITLE
Calendar UX fixes

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#414]
## Expected Behavior

![image](https://github.com/SuperteamDAO/earn/assets/67309069/c673aeac-6465-4fc5-adb5-ee6b097e637f)
the calendar in the create listing form should open up when clicked anywhere on the bounding box

## Actual Behavior
It opens only after the icon is clicked on.

## Suggestions about the UX Improvements:
1. Calendar should pop when anything is clicked
2. Provide small pills of "1 week, two week" etc to add deadline with just one click

**Comment by tarunclub** [comment]
can I take this issue?

**Comment by a20hek** [comment]
> I can help with this issue please assign it to me

you can start working on this

**Comment by MIDZTECHNOLOGY** [comment]
I'll like to work on this issue

**Comment by a20hek** [comment]
can start working on any issues without worries!
no need to ask for a permission. we believe in permissionless work here @MIDZTECHNOLOGY
