### ISSUE TITLE
Sponsor Dashboard floating copy

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#415]
## Expected Behavior

Hovering on each stat should give more information about the same, similar to the following:
![image](https://github.com/SuperteamDAO/earn/assets/67309069/731ba492-1411-479d-860b-a7ebe9a66864)

## Actual Behavior

<img width="948" alt="image" src="https://github.com/SuperteamDAO/earn/assets/67309069/5bd648cd-9377-455e-954b-57e2a363b57c">
These stats have no hover interaction.

## Steps to Reproduce the Problem

1. Create a sponsor profile
2. route to `/dashboard/listings`

**Comment by mb-008** [comment]
hey @a20hek  i have added the tooltip component but what text do you want to display in the tooltip could you be more specific. attaching ss of what i have done :
![tooltip ss](https://github.com/SuperteamDAO/earn/assets/97526225/936ab04c-a163-4c09-a628-7edb7a9dc79d)
Will create a PR if you approve
