### ISSUE TITLE
Change the error message for discord field is not filled in the talent creation flow

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#417]
## Actual Behavior
<img width="540" alt="image" src="https://github.com/SuperteamDAO/earn/assets/67309069/6d6d51ce-3d55-451b-89fb-6d724bf6b88b">

## Expected Behaviour
When discord is not filled (but something else is), we should show a different error.

## Steps to Reproduce the Problem

1. Start the talent profile creation process
2. In the socials field, try proceeding without adding the discord link

**Comment by Shiva953** [comment]
would like to take this up!
