### ISSUE TITLE
Alignment and Spacing Enhancements Needed in Rewards Section of Detailed Listings Page

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#418]
## Actual Behaviour

<img width="434" alt="image" src="https://github.com/SuperteamDAO/earn/assets/67309069/f7e33725-d58e-44e9-bdd4-282d53e93125">

The podium prize split elements are not middle aligned to the top and bottom borders
<br/>
<img width="447" alt="image" src="https://github.com/SuperteamDAO/earn/assets/67309069/1a5b95e3-70ba-4fc5-bb79-8a15c842d440">

When a listing is in draft and has no rewards added, the submissions elements is too close to the border above it

## Suggestions for Improvement:

For the Podium Prize Split Alignment: Adjusting the vertical alignment of the podium prize split elements to be centrally positioned within their container could enhance the visual balance and overall aesthetic appeal of the interface.

For the Draft Listing Spacing: Increasing the margin or padding above the submissions element in draft listings could provide a more spacious and less cluttered appearance, potentially improving readability and user experience.

Looking forward to any additional insights or suggestions

**Comment by ATREAY** [comment]
gm @a20hek, Can I work on this issue?

**Comment by a20hek** [comment]
> gm @a20hek, Can I work on this issue?

you can take it up @ATREAY
