### ISSUE TITLE
Enhancement: Use Actual Title for Listing Slug Instead of Template Title

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#419]
## Current Behavior
When a new draft is created using a template, the system currently utilizes the template's title as the slug for the listing link. This behaviour can lead to situations where the URL does not accurately reflect the final title given to the listing by the sponsor, potentially causing confusion or misalignment between the listing content and its corresponding URL.

## Expected Behaviour
It would be more intuitive and representative if the slug for the listing link were generated based on the actual title provided by the sponsor for the listing, rather than the template title. This change would ensure that the URL is a more accurate reflection of the listing's content, improving clarity and user experience.

## Steps to Reproduce the Problem
1. Create a listing using your sponsor profile
2. Select a template, and save the listing as draft

**Comment by gulshanpr** [comment]
I would like to try this.

**Comment by a20hek** [comment]
go on @gulshanpr

**Comment by gulshanpr** [comment]
on the main website this issue does exists, once a bounty/project is drafted the title/slug isn't changing on changing the title. but when i build the website using the source code there are couples of issue i noticed,
1. when creating a bounty/project there is only one template (start from scratch and nothing else), but on the actual website these is couples of templates. (i think all templates are not available in github's source code)
2. when a bounty/project is drafted first time and then edited and drafted on second time, it does not let me either save as draft or let me publish.

could you confirm these changes?
