### ISSUE TITLE
Search not working in Submissions dashboard

### ISSUE THREAD

**Issue by jim4067** [SuperteamDAO/earn#425]
## Expected Behavior
Text search should show submission either by matching the name of email in the submissions dashboard.

## Actual Behavior
No results are displayed when searching in the submissions dashboard.

## Steps to Reproduce the Problem

1. Receive submissions for a bounty.
2. Search for a particular user

This is useful when we have to cross-check that the submissions have signed up, filled another form or signed up for a platform that is being tested and we need to confirm that they actually signed up using email from our end.

**Comment by a20hek** [comment]
name search seems to be working fine. i think it's the email search that needs to be added

**Comment by a20hek** [comment]
have been implemented: https://github.com/SuperteamDAO/earn/pull/480
