### ISSUE TITLE
Bug: Unable to Login via Email on Local Setup - Looking to Contribute Signup/Login Functionality and Test Users

### ISSUE THREAD

**Issue by tarunclub** [SuperteamDAO/earn#449]
## Expected Behavior
I am unable to log in via email on my local setup. I would love to contribute by adding signup and login functionalities, as well as incorporating some test users for local setup. Thank you!

## Actual Behavior
<img width="1163" alt="Screenshot 2024-02-26 at 10 40 39 PM" src="https://github.com/SuperteamDAO/earn/assets/102040059/4d4df75b-6f27-4871-ac7d-d7faa1e92b1a">

resend dashboard
<img width="991" alt="Screenshot 2024-02-26 at 10 42 02 PM" src="https://github.com/SuperteamDAO/earn/assets/102040059/ff47da3b-8acd-4d2d-b667-a0aaa7cf220b">

## Steps to Reproduce the Problem

1. go to homepage
2. click on login
3. login though email

**Comment by a20hek** [comment]
Sign up and login works for all contributors. Might be that there is some issue from your end. lmk

**Comment by a20hek** [comment]
closing this since this seems to be an issue that you are facing with incorrect setup. reach out to me on twitter if you need help setting stuff up
