### ISSUE TITLE
FEAT: DARK THEME

### ISSUE THREAD

**Issue by apneduniya** [SuperteamDAO/earn#462]
## Expected Behavior
There should be a dark mode so that if we are working at night then our eyes will less strain.

## Actual Behavior
There is no option for it in the whole dashboard.

## Steps to Reproduce the Problem
1. Go to the dashboard.
2. Search for a Dark theme toggle.

This is very useful feature as many are developers here like me who are always comfortable with dark theme.

**Comment by a20hek** [comment]
thank you for taking the time to suggest a dark mode feature @apneduniya, but we've decided to not go ahead with this based on current project priorities, as we think it's more important to direct our efforts towards our core goals

look into extensions like "dark reader" for now

thanks again for your suggestion
