### ISSUE TITLE
Minor bugs in Submit Form

### ISSUE THREAD

**Issue by Manice18** [SuperteamDAO/earn#472]
## Expected Behavior

1. When we click outside of the submit form, it should close.
2. It's better to disable the submit button until all the required fields are filled.

## Actual Behavior

1. The submit form doesn't close when clicked outside.
2. The submit button is not disabled and is less clickable by default ( We can make its bg-color have less opacity or a faded bg works too).

## Steps to Reproduce the Problem

Here is a video to reproduce the problem:

https://github.com/SuperteamDAO/earn/assets/91601706/492688e9-3f7c-4dac-b08b-e7fbc0c072cf

**Comment by a20hek** [comment]
sorry, but it's intended to work this way
