### ISSUE TITLE
Allow sponsors to edit their sponsor profiles

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#477]
This issue is a paid bounty live on Superteam Earn right now, with a prize pool of $75 USDC. Check it out [here](https://earn.superteam.fun/listings/bounty/st-earn-oss-issue-allow-sponsors-to-edit-their-profiles/).

## Expected Behavior
Sponsors should be able to edit their profile details from the sponsor dashboard. To make that happen, the sponsor dashboard needs the following:
1. An edit icon next to the Sponsor name on the dashboard
If the sponsor name is too big and could break the UI, truncate the name such that the edit icon is visible and not interfering with the vertical light grey line on its right
<img width="529" alt="image" src="https://github.com/SuperteamDAO/earn/assets/67309069/7977aa3b-0fc2-4eb6-b47e-35cf044ea992">
2. Clicking on the edit icon should take them to a pre-filled sponsor profile creation form, where all fields are editable
Add checks for duplicates of username/company name, twitter, etc.
Change CTA copy to “Update Profile”
<img width="656" alt="image" src="https://github.com/SuperteamDAO/earn/assets/67309069/d8e8944f-743b-4816-99a2-6a8a90e95529">
3. Once the profile is updated, redirect them to the dashboard

## Actual Behavior
Often the name or PFP of the sponsor needs to be updated which has to be done manually — this helps save time for the sponsor and reduce their dependency on the Earn team.

**Comment by kirtiraj22** [comment]
hey @a20hek , I would like to work on this issue.🫡

**Comment by Sajal0208** [comment]
Hey @a20hek, I would like to work on this issue. 

I am done with setting up my local environment.

**Comment by a20hek** [comment]
everyone can start working simultaneously. since this is a bounty, I won't be assigning this issue to anyone
will be treated on a FCFS basis. The best implementation will get merged

**Comment by neutr0n420** [comment]
let me also give it a try

**Comment by bigjoefilms** [comment]
let give this a try

**Comment by neutr0n420** [comment]
is this issue already done @a20hek ?? I see the a merged PR for this one

**Comment by a20hek** [comment]
can attempt for the second prize @neutr0n420
