### ISSUE TITLE
Make listing URL/slugs editable during listing creation

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#479]
This issue is a paid bounty live on Superteam Earn right now, with a prize pool of $75 USDC. Check it out [here](https://earn.superteam.fun/listings/bounty/st-earn-oss-issue-make-listing-slugs-editable/).
## Expected Behavior
Pre-fill the auto-generated slug whenever a new listing title is added to the listing creation flow. Allow users to edit the slug while checking for duplicates. If the slug already exists show an error message right below the field in red text (same component as used for social link errors, or duplicate sponsor profile names error for example). 
 
Duplicate the Listing Title field component for style, etc. The slug field should be right below the Listing Title field.

## Actual Behavior
Right now it’s not possible to do this from the frontend.

**Comment by Shiva953** [comment]
would like taking this up!

**Comment by a20hek** [comment]
everyone can start working simultaneously. since this is a bounty, I won't be assigning this issue to anyone
will be treated on a FCFS basis. The best implementation will get merged
