### ISSUE TITLE
[Bug] - Error while liking the submission

### ISSUE THREAD

**Issue by Not-Sarthak** [SuperteamDAO/earn#482]
https://github.com/SuperteamDAO/earn/assets/92942966/9d389414-c0e8-42cb-84c7-d2050ee9fffd

## Expected Behavior
On clicking the like button the user should be able to like the submission thereby increasing the counter of like by 1
## Actual Behavior
Gives error as shown in video above

**Comment by a20hek** [comment]
because you are not logged in @Not-Sarthak  :)
