### ISSUE TITLE
Add Docker compose for database setup

### ISSUE THREAD

**Issue by Manice18** [SuperteamDAO/earn#569]
## The Problem:
Setting up a database each time is time-consuming and can introduce initial configuration errors. This process involves installing software, configuring settings, and ensuring compatibility, which often leads to inefficiencies and potential issues.

## Solution:
Utilizing Docker simplifies the process by allowing users to effortlessly spin up the database according to predefined configurations, eliminating the need for repetitive setup tasks.

**Comment by a20hek** [comment]
you dont have to set up a database "each time"
its just a one time setup thing – similar to how docker does it.

this issue is more aligned with the convenience of having multiple ways to set up
