### ISSUE TITLE
Ability to remove team members from a Sponsor Dashboard

### ISSUE THREAD

**Issue by a20hek** [SuperteamDAO/earn#581]
## Expected Behavior
- Each member row should display a "Remove" button.
- Upon clicking the "Remove" button, a confirmation modal should appear with the following details:
  - Title: "Remove Member?"
  - Subtext: "Are you sure you want to remove `<email>` from accessing your sponsor dashboard? You can invite them back again later if needed."

**Comment by Sajal0208** [comment]
Picking up this issue!
