### ISSUE TITLE
Integrate the Earn API to retrieve new bounties (for Telegram/WhatsApp bot)

### ISSUE THREAD

**Issue by codewithmide** [SuperteamDAO/earn#605]
Dear Superteam Earn Developers,

I'm writing to inquire about the possibility of integrating the Superteam Earn platform's API to retrieve information on newly listed bounties. I'm developing a Telegram/WhatsApp bot that would notify users about these fresh opportunities.

My specific questions are:

1. **Does Superteam Earn offer a public API for developers?** If so, could you please provide a link to the API documentation or any relevant resources?
2. **If an API is not available, are there alternative methods** (e.g., web scraping) to access data on new bounties? Any guidance you can offer would be greatly appreciated.
3. **What data points are available about newly listed bounties through the API or other methods?** Ideally, I'd like to retrieve information such as:
- Bounty title
- Bounty description
- Reward amount
- Deadline or duration
- Any relevant links (e.g., bounty details page)

I understand that this might require some additional development effort on your end, but I believe it would be a valuable addition to the Superteam Earn ecosystem, allowing users to stay informed about new bounties through their preferred messaging platforms (Telegram/WhatsApp).

**Comment by a20hek** [comment]
hey @codewithmide , love the initiative here. but unfortunately, we dont have plans to make an API as of now. and, we don't recommend scraping since it might not give you accurate data
