### ISSUE TITLE
Ui bug in mobile view of Submit now button 

### ISSUE THREAD

**Issue by rahulsingh2312** [SuperteamDAO/earn#619]
## Expected Behavior
The submit now button should appear bit above , the bottom nav as it is currently not visible 
## Actual Behavior
<div style="display: flex; flex-wrap: nowrap;">
    <img src="https://github.com/SuperteamDAO/earn/assets/111289008/f622347e-31df-4890-91a3-939ebbaf5b84" alt="earnbug2" width="150" style="margin-right: 10px;">
    <img src="https://github.com/SuperteamDAO/earn/assets/111289008/8fd5fe6a-4a5c-4e16-8ff0-7ce39e9f0ab3" alt="earnbug" width="150" style="margin-right: 10px;">
    <img src="https://github.com/SuperteamDAO/earn/assets/111289008/c17ca597-0656-48b1-a31d-f34bc5e2c6c4" alt="earn" width="150" style="margin-right: 10px;">
    <img src="https://github.com/SuperteamDAO/earn/assets/111289008/e22b5439-cea8-48d9-8d70-d08129782638" alt="Earn bug" width="150" style="margin-right: 10px;">
</div>

## Steps to Reproduce the Problem

1. Go to mobile view and click on any bounty or any card.
2. Finding the reason why that is not visible, it's mostly because of the new bottom navbar
3. will try to put that above the navbar

**Comment by rahulsingh2312** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by a20hek** [comment]
thanks for raising and solving this!
