### ISSUE TITLE
Overflow:X Ui Bug in mobile view for Winner of project 

### ISSUE THREAD

**Issue by rahulsingh2312** [SuperteamDAO/earn#622]
## Expected Behavior
it should fit properly in mobile view , the bar should not be that wide in mobile view same for winner profile should be center and no overflow
lastly grants submit button , should be bit above

## Actual Behavior

<div style="display: flex; flex-wrap: nowrap;">
    <img src="https://github.com/SuperteamDAO/earn/assets/111289008/9faa5f03-62ef-465d-a3d1-f8444d0ef1d0" alt="earnbug2" width="33%" style="margin-right: 10px;">
    <img src="https://github.com/SuperteamDAO/earn/assets/111289008/e19e4c20-e474-47fa-ba53-66458ab50a45" alt="earnbug" width="33%" style="margin-right: 10px;">
    <img src="https://github.com/SuperteamDAO/earn/assets/111289008/9b34ca9f-c4bd-4589-a132-bb7f32cec680" alt="earn" width="33%" style="margin-right: 10px;">
</div>

## Steps to Reproduce the Problem

1. Check any Project or bounty which have any winner announced in mobile view
2. Check any grant in mobile view

**Comment by a20hek** [comment]
you can start work permissionlessly @rahulsingh2312
