### ISSUE TITLE
Feat Request: Containerization 

### ISSUE THREAD

**Issue by Gautam-Hegde** [SuperteamDAO/earn#629]
### Implement Docker containerization and Docker Compose for: 

- streamlined development setup 
- consistent environment across different platforms.

if approved I would like to work towards its implementation.

**Comment by a20hek** [comment]
curious: what issues are you facing with the current setup

**Comment by Gautam-Hegde** [comment]
> curious: what issues are you facing with the current setup @Gautam-Hegde

It would be fairly straightforward to spin up a postgres container rather than relying on an external provider for dev env.
