### ISSUE TITLE
Bounty page listing order wrong.

### ISSUE THREAD

**Issue by brighton-ifaya** [SuperteamDAO/earn#655]
## Expected Behavior
On the Home page https://earn.superteam.fun/bounties/ it is expected that the listing shows order of bounties according to time left to expiry.
![Screenshot_20240715_080423](https://github.com/user-attachments/assets/0ad81e3c-3d79-48ee-b880-7c1a9d17e78a)

## Actual Behavior
However the listing does this:
![Screenshot_20240715_080329](https://github.com/user-attachments/assets/799f4ba4-351a-4a27-ba25-2d46e2efc0e1)

The user has to click `view all` to see the listing in the correct order.
@a20hek

**Comment by Emmanueltech** [comment]
I would like to reserve this task

**Comment by a20hek** [comment]
Thanks for pointing this out @brighton-ifaya !
We've fixed this!
