### ISSUE TITLE
Regions Feature missing "global" as an option

### ISSUE THREAD

**Issue by brighton-ifaya** [SuperteamDAO/earn#682]
## Expected Behavior
The recent `regions` feature should show the "global" option among the selectable regions.

![Screenshot_20240810_015234](https://github.com/user-attachments/assets/198f3e09-19ce-4d04-84b8-3ce1ad5afa26)

## Actual Behavior
However once user selects a region, the global option dissapears. this means user has to either remove the extra path on the address bar or reload the bounties/projects page to see the globally available bounties/projects again.

![Screenshot_20240810_015150](https://github.com/user-attachments/assets/c6cb49ca-f852-4e32-a739-426c0b6205ba)

@a20hek

**Comment by scienmanas** [comment]
I will work on this. Will do it tomorrow.

**Comment by Mihir867** [comment]
I have worked on this and i think its a scalable option, do check this out @a20hek
