### ISSUE TITLE
Bug: Responsiveness

### ISSUE THREAD

**Issue by Not-Sarthak** [SuperteamDAO/earn#694]
## Expected Behavior
The content should be wrapped inside a div of responsive width sizes.

## Actual Behavior
![image](https://github.com/user-attachments/assets/d6b3306d-3cf1-47d3-bbf6-f48907843710)

## Steps to Reproduce the Problem

1. Visit: https://earn.superteam.fun/listings/bounty/phalcon-bounty/
2. Scroll Down to Details Tab

**Comment by a20hek** [comment]
thanks for reporting, although the solution you proposed wasn't what went wrong here
