### ISSUE TITLE
Improper rendering of variable bounty price when it's in a range

### ISSUE THREAD

**Issue by scienmanas** [SuperteamDAO/earn#749]
As seen from the photo below, this issue seems to be a bit small and can be fixed quickly by me. Happens in oneplus nord 2T

## Expected Behavior

Actual behavior is no overlapping.

## Actual Behavior

![Screenshot_2024-09-16-19-22-06-76_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/faffbd31-0a89-4799-a303-b0ceecb4f396)

## Steps to Reproduce the Problem

1. Use phone for searching bounties.
2. Can be easily reproduced using on phone check - Solgotchi development bounty

**Comment by JayeshVP24** [comment]
hey @scienmanas 
can you confirm if this still exists for your issue?

its working well for our devices now

here is the link
[https://earn.superteam.fun/listings/project/solgotchi-enhanced-development/](https://earn.superteam.fun/listings/project/solgotchi-enhanced-development/)

please confirm, thank you!

**Comment by scienmanas** [comment]
> hey @scienmanas 
> can you confirm if this still exists for your issue?
> 
> its working well for our devices now
> 
> here is the link
> [https://earn.superteam.fun/listings/project/solgotchi-enhanced-development/](https://earn.superteam.fun/listings/project/solgotchi-enhanced-development/)
> 
> please confirm, thank you!

**Yes the issue is resolved now. It appears as it should be.** 

![Screenshot_2024-12-05-12-29-45-18_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/f469e985-021f-4779-8c9a-e2c5b8daaa70)
