### ISSUE TITLE
BUG - LinkedIn Profile Information Not Saving Correctly

### ISSUE THREAD

**Issue by vczb** [SuperteamDAO/earn#854]
## Expected Behavior
After saving my profile with LinkedIn information, I expect the value to appear correctly on my profile.

## Actual Behavior
Although the data is updated, the LinkedIn value appears as null.

## Steps to Reproduce the Problem

1.     Go to your profile.
2.     Add LinkedIn information.
3.     Save the profile.
4.     View the profile.

https://github.com/user-attachments/assets/7610879b-74bc-4126-b96e-82ba9e9677a0

![image](https://github.com/user-attachments/assets/8626ef99-fcf2-4d3b-a1be-6d0f999119fa)

**Comment by scienmanas** [comment]
> ## Expected Behavior
> 
> After saving my profile with LinkedIn information, I expect the value to appear correctly on my profile.
> ## Actual Behavior
> 
> Although the data is updated, the LinkedIn value appears as null.
> ## Steps to Reproduce the Problem
> 
>     1. ```
>        Go to your profile.
>        ```
> 
>     2. ```
>        Add LinkedIn information.
>        ```
> 
>     3. ```
>        Save the profile.
>        ```
> 
>     4. ```
>        View the profile.
>        ```
> 
> 
> Screencast.From.2024-12-01.14-26-49.mp4
> 
> ![image](https://private-user-images.githubusercontent.com/51221635/391350811-8626ef99-fcf2-4d3b-a1be-6d0f999119fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTAyOTIsIm5iZiI6MTczMzM4OTk5MiwicGF0aCI6Ii81MTIyMTYzNS8zOTEzNTA4MTEtODYyNmVmOTktZmNmMi00ZDNiLWExYmUtNmQwZjk5OTExOWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNTdiOTNmNTQ0ZTk0Yjk0YjY5MzFlZDcyZjgzZjNhMmE1NGZjZGNmODQ5MDQ5M2QxMmQ4NWY3OWIwY2FiYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._YG2otO66uKlOWsKRTvrAZ_uSZYLnF4YVN34z-EsC0E)

I think its working perfectly, just added my linkedin and it was working perfectly, it was able to fetch, maybe some saving problem at your side. But yeah this t.me ui problem is there . 
![image](https://github.com/user-attachments/assets/4d406d71-604b-432a-8f90-501b2e032e84)

**Comment by scienmanas** [comment]
I will fix the ui part and will make a pull request

**Comment by vczb** [comment]
Check this video 

https://github.com/user-attachments/assets/3e44eae3-f2bd-4809-8df4-b1c6cce5f9af

**Comment by scienmanas** [comment]
> Check this video 
> 
> https://github.com/user-attachments/assets/3e44eae3-f2bd-4809-8df4-b1c6cce5f9af
> 
> 

I will make a new account and check.

**Comment by vczb** [comment]
Hey! I found the issue; it’s here: https://github.com/SuperteamDAO/earn/blob/82a92fc5dfcc56cd598f40f77fb85780b19deecd/src/features/talent/utils/extractUsername.ts#L46. 

According to this regex, the minimum character length is 5, but my profile has only 4.

I will fix it by sending a PR to reduce the minimum to 3, as specified in the LinkedIn documentation.

![image](https://github.com/user-attachments/assets/855820d0-7207-40c1-bdae-35a1c3864b06)

**Comment by scienmanas** [comment]
Ok.
