### ISSUE TITLE
Missing information about zerobounce

### ISSUE THREAD

**Issue by vczb** [SuperteamDAO/earn#855]
# Add Zerobounce Setup Instructions to CONTRIBUTING.md and .env.example

## Summary

The Zerobounce integration is missing setup instructions, which can cause confusion for new developers. This issue proposes adding clear guidance to the `CONTRIBUTING.md` file and including the necessary variable in `.env.example`.

## Expected Behavior

- The `CONTRIBUTING.md` file includes setup steps for Zerobounce integration.
- The `.env.example` file contains the required Zerobounce environment variable.

## Actual Behavior

- There is no documentation in the `CONTRIBUTING.md` file about configuring Zerobounce.
- The `.env.example` file does not include the necessary Zerobounce variable.
- Without proper setup, the Zerobounce functionality in the following file results in `undefined` and does not work:

  [src/pages/api/email/validate.ts#L20](https://github.com/SuperteamDAO/earn/blob/49c305d7a367f78ff29175948aebf690804d08b7/src/pages/api/email/validate.ts#L20)

![image](https://github.com/user-attachments/assets/9a573ce6-4675-49b7-90e4-2b70e69dc31a)

## Steps to Reproduce

1. Clone the repository.
2. Run the application without setting up Zerobounce.
3. Try to log in with email

![image](https://github.com/user-attachments/assets/5ceda477-f8ed-42be-ba6b-980958892ffa)

**Comment by Kishan-Patel-dev** [comment]
Hi @vczb,
I'd like to work on this issue to add the Zerobounce setup instructions to the CONTRIBUTING.md file and update the .env.example with the required variable. Could you please assign it to me? Let me know if there are any additional details or specific guidelines to follow.

Thanks!

**Comment by vczb** [comment]
> Let me know if there are any additional details or specific guidelines to follow.

Hey @Kishan-Patel-dev , thanks for your interest in working on this issue!

I'm just an enthusiast on this project, so I don't have the privileges to assign users to tickets. 
However, feel free to go ahead and push a pull request and link it to the ticket—I think that would work perfectly fine.

| _Let me know if there are any additional details or specific guidelines to follow._

No additional context is needed beyond what’s described in the ticket and the best practices outlined in the CONTRIBUTING guide. I recommend following an approach similar to the Resend instructions:

![image](https://github.com/user-attachments/assets/a3693748-745b-450f-863a-d41964dddf79)

---

Tagging @a20hek as a major contributor to share any recommendations they might have.

**Comment by vczb** [comment]
Hey @Kishan-Patel-dev I noticed we also have a similar information on the README 
![image](https://github.com/user-attachments/assets/9d2dab3a-e419-458e-9f8a-5f85419092de)

Maybe you can consider to include it as well :)

**Comment by a20hek** [comment]
i feel its better to not include zerobounce validation on non-production environments rather than including that as an extra step during setup. thoughts?

**Comment by a20hek** [comment]
fixed on `staging` branch
thanks again!
